#!/bin/bash
echo "Démarrage de l'application Shopie Backend..."
echo ""
echo "Configuration requise:"
echo "- Java 21 ou supérieur"
echo "- MySQL 8.0+ en cours d'exécution"
echo "- Base de données 'shopie_db' créée"
echo ""
echo "Endpoints principaux:"
echo "- API: http://localhost:8080/api"
echo "- Swagger: http://localhost:8080/api/swagger-ui.html"
echo ""
echo "Comptes de test:"
echo "- Admin: admin@shopie.com / password"
echo ""
read -p "Appuyez sur Entrée pour continuer..."
mvn spring-boot:run